### ISSUE TITLE
I faced on the build-error of ndarray/Boost.Numpy in the Dockerfile based on Ubuntu18.04LTS

### ISSUE THREAD

**Issue by yoshihingis** [ndarray/Boost.NumPy#87]
(1)Issue
I used the Dockerfile with bese of Ubuntu16.04 , CUDA10.1 and cuDNN7.
I changed host OS from Ubuntu 16.04LTS to Ubuntu18.04LTS.
Hence I changed the base of Dockerfile as below;

(Pervious)  FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04
(Current)   FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

I only changed the base of Dockerfile, but I faced on the build Error of ndarry/Boost.Numpy. 
Docker file is as below;
[Dockerfile.txt](https://github.com/ndarray/Boost.NumPy/files/4709568/Dockerfile.txt)

I did not face on build the error with previous Dockerfile which used Ubuntu16.04LTS base. 

Build Error as below;
![build_error](https://user-images.githubusercontent.com/18341725/83379180-e0bd6b00-a415-11ea-96b7-7cd29a2d7fe8.jpg)

How do I delete this issue?
Why does the build error occur only with the changing of Base Ubuntu version of Dokcerfile? 
I'd really appreciate it if anyone give me good advice! 

2)Envirment
OS : Ubuntu18.04LTS
CUDA 10.2
Docker : 19.03.9
 
Regards,

**Comment by TallJimbo** [comment]
This looks like a basic link error problem (as if your binary was not being linked to `libboost_numpy.so` at all).  I don't have any good guesses at how a tool chain could cause that, as is this is the kind of symptom that can have many causes.

But I'm afraid I'm not a Docker user myself, and this library is no longer being maintained.  You will be able to find more support if you can switch to the built-in NumPy bindings that have now been included directly in Boost.Python for a while.  Those have essentially the same interface, but are in namespace `boost::python::numpy` instead of `boost::numpy`.

**Comment by yoshihingis** [comment]
Dear TalUimbo

Thank you for your reply and sorry for my delay.

I could not identify the underlying cause of this issue,but I found the way to resolve this issue.

When the Dockerfile,which uses the base of ubuntu16.04 ,Cmake detects the folder /usr/local/lib64 was installed libbost_numpy.so.

But  the Dockerfile,which uses the base of ubuntu18.04, Cmake can not detect the folder /usr/local/lib64 ,hence link error happens.

・The way of resolving this issue/
 I added Path of /usr/local/lib64 to Makefile.config  for the building of CAFFE, the link error did not happened.

Regards,
Regards
